### ISSUE TITLE
Auto ignore *.Source.SourceProject.props files.

### ISSUE THREAD

**Issue by walterlv** [dotnet-campus/SourceYard#26]
It's recommended to ignore *.Source.SourceProject.props files automatically.

What you should do is to add a .ignore file with content shown below:

```
/.gitignore
/*.Source.SourceProject.props
```

Tips:

1. The `/` is necessary for ignoring files in this exact folder instead of ignoring files recursively.
1. `/.ignore` is a necessary line to ignore the .ignore file itself.
1. You should not use .gitignore name for the file, because you can't ignore it in our SourceYard project. This file can only have the target name after packing.

**Comment by lindexi** [comment]
https://github.com/dotnet-campus/SourceYard/projects/1#card-13415893
