### ISSUE TITLE
编译期间概率性出现文件被占用的问题

### ISSUE THREAD

**Issue by walterlv** [dotnet-campus/SourceYard#44]
EXEC : error : 生成源码包: NuGetPacker: System.IO.IOException: 文件“D:\Developments\Walterlv\Walterlv.Demo.Package\bin\Debug\Walterlv.Demo.Package.8.0.0.nupkg”正由另一进程使用，因此该进程无法访问此文件。

**Comment by walterlv** [comment]
如果使用以下代码，此问题几乎必现

```xml
<PropertyGroup>
    <TargetFrameworks> netstandard2.0;net45;net451;net452;net46;net461;net462;net47;net471;net472;net48 </TargetFrameworks>
</PropertyGroup>
```

**Comment by walterlv** [comment]
Reopen this issue?

**Comment by hueifeng** [comment]
@lindexi  @walterlv I found here https://github.com/dotnet-campus/dotnetCampus.Configurations/runs/687420475 also seems to be due to the error caused by the problem.

**Comment by walterlv** [comment]
@hueifeng Yes, you're right. I'm trying to find out some solutions.

**Comment by walterlv** [comment]
Fixed: https://github.com/dotnet-campus/SourceYard/pull/74
