### ISSUE TITLE
希望可以将源代码包引入的类型设置为 internal

### ISSUE THREAD

**Issue by walterlv** [dotnet-campus/SourceYard#48]
需求：

1. 做一个库，对外发布 NuGet 包；
2. 此库需要用到一些通用的工具类，但仅仅辅助完成此库中其他关键功能的实现；

问题：

1. 如果此库对外公开时将源代码包的 API 也开放了，那么会导致泄漏一些非此库公开的 API，使得此库纯粹；
2. 在以下情况下，此问题更为严重：
    - 此库仅仅实现很少功能，但源代码包却占了大多数 API
    - 此库与源代码包都是同一个作者，命名空间前缀相同，于是此库提供的 API 中同一个命名空间下会有很多不同种类的类型

解决：

- 希望能够将所有的源代码包引入的类型设置为 `internal`，以便让工具更为纯粹

参考：

- 微软的 ILMerge 和社区的 ILRepack 都提供了将合并类型改为 `internal` 的选项，因此这种行为是有先例的

**Comment by lindexi** [comment]
建议将这个行为作为一个依赖SourceYard的另一个库

**Comment by lindexi** [comment]
放在 https://github.com/dotnet-campus/dotnetCampus.SourceYard.Extras
