### ISSUE TITLE
The source package is not been built in multiple TargetFrameworks project.

### ISSUE THREAD

**Issue by walterlv** [dotnet-campus/SourceYard#57]
This issue comes since 0.1.17753-alpha and 0.1.17751-alpha works fine.

See this image below and you'll find that the source package does not exist in the output folder.

![image](https://user-images.githubusercontent.com/9959623/70967120-58017b80-20d0-11ea-9e6f-70da891c7cbc.png)

**Comment by wuyu8512** [comment]
+1，希望使用TargetFrameworks时也可以生成源代码包

**Comment by walterlv** [comment]
@wuyu8512 如图，你降两个版本就可以使用了，使用 17751

**Comment by wuyu8512** [comment]
> @wuyu8512 如图，你降两个版本就可以使用了，使用 17751

感谢，使用17750后正常使用了，另外发现多框架时生成后的项目引用有点问题，需要自己修改nuspec

**Comment by walterlv** [comment]
@wuyu8512 报了一个 #52，是这个吗？
如果不是，可以把你的问题也说出来，这边尽可能解决掉。

**Comment by wuyu8512** [comment]
@walterlv 相同的问题，我现在直接从原始nuspec里替换修改了，另外，如果项目引用另一个源码包，生成后的源码包会里没有这个引用

**Comment by walterlv** [comment]
@wuyu8512 +1，源码包也要加上。我这几天试着修一下吧，感兴趣再提一个 issue？

**Comment by walterlv** [comment]
@wuyu8512 问题已经修复了，更新到 19003 即可，感谢 @lindexi
