### ISSUE TITLE
提供额外带上文件的方法

### ISSUE THREAD

**Issue by lindexi** [dotnet-campus/SourceYard#75]
可以使用 PackSource 属性指定将某个文件或文件夹打包到源代码包的某个文件夹或文件

如下面写法 

               <PackSource Include = "Foo\123.dll" OuputPath = "\analyzer\123.dll"/>

**Comment by lindexi** [comment]
按照约定的文件夹


	- _nuget_
		- .gitignore
		- analyzers
		- ~~build~~
		- ~~buildMultiTargeting~~
		- ~~src~~
		- runtime

**Comment by lindexi** [comment]
<CompilePackSourceYard Include = "Foo\123.dll" OuputPath = "\analyzer\123.dll"/>

**Comment by walterlv** [comment]
@lindexi 

```xml
<SourceYardCompile Include="Foo\a.cs" SourcePackagePath="analyzer\a.cs" />
<SourceYardNone Include="Foo\123.dll" SourcePackagePath="analyzer\1.dll" />
```
